"""HTML renderer for tearsheet reports.

Assembles section HTML fragments into a complete, self-contained HTML
document with inline CSS. Follows Stephen Few's design principles:
minimal decoration, high data-ink ratio, and purposeful colour usage.
"""

from __future__ import annotations

__all__ = ["render_html"]

_CSS = """
body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
                 "Helvetica Neue", Arial, sans-serif;
    max-width: 960px;
    margin: 0 auto;
    padding: 20px 40px;
    color: #333;
    background: #fff;
    line-height: 1.5;
}
h1 {
    font-size: 24px;
    font-weight: 600;
    border-bottom: 2px solid #4a7c9b;
    padding-bottom: 8px;
    margin-bottom: 4px;
}
.subtitle {
    color: #666;
    font-size: 14px;
    margin-bottom: 24px;
}
.commentary {
    background: #f8f9fa;
    border-left: 3px solid #4a7c9b;
    padding: 12px 16px;
    margin-bottom: 24px;
    font-style: italic;
    color: #555;
}
h2 {
    font-size: 18px;
    font-weight: 600;
    color: #2c3e50;
    margin-top: 32px;
    margin-bottom: 12px;
}
h3 {
    font-size: 15px;
    font-weight: 600;
    color: #34495e;
    margin-top: 16px;
}
.section {
    margin-bottom: 32px;
}
.metrics-table {
    border-collapse: collapse;
    width: 100%;
    margin: 12px 0;
}
.metrics-table th, .metrics-table td {
    text-align: left;
    padding: 8px 12px;
    border-bottom: 1px solid #e0e0e0;
}
.metrics-table th {
    background: #f5f7f9;
    font-weight: 600;
    font-size: 13px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: #555;
}
.metrics-table td {
    font-size: 14px;
}
.metrics-table tr:hover {
    background: #f8f9fa;
}
.placeholder {
    color: #888;
    font-style: italic;
    padding: 16px;
    background: #f8f9fa;
    border-radius: 4px;
}
img {
    display: block;
    margin: 12px 0;
}
.footer {
    margin-top: 40px;
    padding-top: 12px;
    border-top: 1px solid #e0e0e0;
    font-size: 12px;
    color: #999;
}
@media print {
    body { max-width: 100%; padding: 10px; }
    .section { page-break-inside: avoid; }
}
"""


def render_html(
    sections: list[str],
    title: str = "Portfolio Tearsheet",
    commentary: str | None = None,
) -> str:
    """Render section HTML fragments into a complete HTML document.

    Args:
        sections: List of HTML string fragments from section functions.
        title: Report title.
        commentary: Optional commentary paragraph.

    Returns:
        Complete HTML document as a string.
    """
    commentary_html = ""
    if commentary:
        commentary_html = f'<div class="commentary">{commentary}</div>'

    sections_html = "\n".join(sections)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>{title}</title>
<style>{_CSS}</style>
</head>
<body>
<h1>{title}</h1>
<div class="subtitle">Generated by QuantLite</div>
{commentary_html}
{sections_html}
<div class="footer">Report generated by QuantLite tearsheet engine.</div>
</body>
</html>"""
